### ISSUE TITLE
Issues I'd like to (see) address(ed) (updated 5/23)

### ISSUE THREAD

**Issue by rosecitytransit** [robotastic/trunk-recorder#456]
Some of these I do want to work on and can submit myself, and this is somewhat a note for myself. Others are kind of wish list items or ideas. I've mentioned many of them on Gitter chat.

**MERGED AND GOOD**
- [x] perhaps 0eb05cd (is this an issue for anyone? Need to get other P25 systems set up and see if/how they do unit-unit calls)
- [x] decoding rate chart creator ( f36488f or eb9a000 but also want non-PHP shell script version )
- [x] make log files match console output, include message severity levels (I've done this)
- [x] make Decim messages go to BOOST logging instead of console output https://github.com/robotastic/trunk-recorder/blob/master/trunk-recorder/recorders/p25_recorder.cc#L77 https://github.com/robotastic/trunk-recorder/blob/master/trunk-recorder/recorders/debug_recorder.cc#L61 https://github.com/robotastic/trunk-recorder/blob/master/trunk-recorder/systems/smartnet_trunking.cc#L66 https://github.com/robotastic/trunk-recorder/blob/master/trunk-recorder/systems/p25_trunking.cc#L60
- [x] cleanly exit by closing open calls (including writing JSON files)

**MERGED BUT MAY HAVE ISSUES**
- [x] controlWarnRate message frequency (sometimes I want it every 3 seconds when adjusting antennas, other times 1/min to make sure things are good)
*(see note on commit 2d6a954 and discussion at https://github.com/robotastic/trunk-recorder/pull/470#discussion_r636501481)*
- [x] silenceFrames (3b3fa38) I'm guessing this should really be a boolean like it originally was, that it should do "real time" recording of calls, as in including the silence between transmissions
- [x] detect P25 call terminations and close calls based on them (#451, plan on working on at rosecitytransit/trunk-recorder:newtrimetscanner)
*(see comment at https://github.com/robotastic/trunk-recorder/pull/480#issuecomment-846443248)*
- [x] log call priority and phase 2 slot #
*(priority, and duplex/mode, logging added w/67a0d86, but may not be complete; also slot logging not done)*

**MAYBE OTHERS CAN DO**
- [ ] debugRecorder documentation, both for SDR# and Wireshark (both control channel and calls) use *([Started](https://github.com/robotastic/trunk-recorder/wiki/Using-Debug-Recorders))*
- [ ] possibly a tiny version of trunk-recorder with all call functions removed, for testing location/device/settings/antenna quality based on control channel decoding rate
- [ ] overhaul talkgroup priority handling--record all calls below given threshold, don't limit to # of recorders, set unknown ones as a certain priority level, close lower priority calls if a higher one comes in and no recorders available
- [ ] convert OP25 `fprintf (stderr, "...")` statements to boost logging

**WOULD STILL LIKE TO DO**
- [ ] perhaps make USRP support optional ( 031ffcc )
- [x] per-day call logs and live updating Web page (#153 and as seen on http://kcmscanner.ddns.net/)
- [x] getting radio IDs from voice frames as well as control channel (#200)
